# vim: syntax=yaml textwidth=120 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent
# Docker compose setting up a standalone XTB service on a local docker host.configs:
# NOTE: Source the ENV defining the secret first or define them inline (SSH_KEY, PKI_PASSPHRASE, STATECACHE_PASS)

networks:
  trustbroker-network:
    external: false

services:
  mariadb:
    container_name: mariadb
    restart: on-failure
    image: docker.io/library/mariadb:10.7.6
    volumes:
      - ./mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=TBSS16
      - MYSQL_ROOT_PASSWORD=${STATECACHE_PASS}
      - MYSQL_PASSWORD=${STATECACHE_PASS}
      - MYSQL_USER=trustbroker
    networks:
      - trustbroker-network

  gitea:
    container_name: gitea
    restart: on-failure
    image: docker.io/gitea/gitea:1.21.5
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./gitea:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    networks:
      - trustbroker-network

  ldap:
    container_name: ldap
    image: bitnami/openldap
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      #- BITNAMI_DEBUG=true
      - LDAP_ROOT=dc=trustbroker,dc=swiss
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=secret
      - LDAP_CUSTOM_SCHEMA_DIR=/schema_init
      - LDAP_CUSTOM_LDIF_DIR=/ldif_init
    volumes:
      - ./ldap_init/schema:/schema_init:ro
      - ./ldap_init/ldif:/ldif_init:ro
      #- openldap_data:/bitnami/openldap

  trustbroker:
    container_name: trustbroker
    image: ghcr.io/trustbroker-swiss/trustbroker-application:latest
    user: "${UID}:${GID}"
    depends_on:
      - gitea
      - mariadb
      - ldap
    volumes:
      - ./ssh:/etc/trustbroker/keys:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8090:8090"
      - "8091:8091"
    environment:
      - GIT_URL=${GIT_URL}
      - GIT_TOKEN=${GIT_TOKEN}
      - SSH_KEY=${SSH_KEY}
      - CONFIG_BRANCH=main
      - SPRING_PROFILES_ACTIVE=DEMO
      - PKI_PASSPHRASE=${PKI_PASSPHRASE}
      - SPRING_FLYWAY_URL=jdbc:mariadb://mariadb:3306
      - SPRING_FLYWAY_USER=root
      - SPRING_FLYWAY_PASSWORD=${STATECACHE_PASS}
      - SPRING_DATASOURCE_USERNAME=trustbroker
      - SPRING_DATASOURCE_PASSWORD=${STATECACHE_PASS}
      # Debug SSH startup in case of connectivity problem with external git repo
      #- LOGGING_LEVEL_ROOT=DEBUG
      # When running behind an enterprise proxy inject a HTTPS or SSH proxy (HTTP not supported)
      #- HTTPS_PROXY=http://proxy.company.com:1234
      #- SSH_PROXY_HOST=proxy.company.com
      #- SSH_PROXY_PORT=1234
      # When running on HTTP relax cookie polices
      - TRUSTBROKER_CONFIG_SECUREBROWSERHEADERS=false
    networks:
      - trustbroker-network

  samlmock:
    container_name: samlmock
    image: ghcr.io/trustbroker-swiss/trustbroker-samlmock:latest
    depends_on:
      - gitea
    volumes:
      - ./ssh:/etc/trustbroker/keys:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "7070:7070"
      - "7071:7071"
    environment:
      - GIT_URL=${GIT_URL}
      - GIT_TOKEN=${GIT_TOKEN}
      - SSH_KEY=${SSH_KEY}
      - CONFIG_BRANCH=main
      - SPRING_PROFILES_ACTIVE=DEMO
      - PKI_PASSPHRASE=${PKI_PASSPHRASE}
    networks:
      - trustbroker-network
