DROP TABLE IF EXISTS TB_AUTH_SESSION_CACHE;
CREATE TABLE IF NOT EXISTS TB_AUTH_SESSION_CACHE
(
	SESSION_ID           VARCHAR(255) PRIMARY KEY,
	SP_SESSION_ID        VARCHAR(255),
	SSO_SESSION_ID       VARCHAR(255),
	OIDC_SESSION_ID      VARCHAR(255),
	EXPIRATION_TIMESTAMP TIMESTAMP NOT NULL,
	DATA                 MEDIUMTEXT
);