-- JWK set rotated by the JwkCacheService according based on keySchedule
DROP TABLE IF EXISTS TB_AUTH_JWK_CACHE;
CREATE TABLE IF NOT EXISTS TB_AUTH_JWK_CACHE
(
	KEY_ID               VARCHAR(255) PRIMARY KEY,
	EXPIRATION_TIMESTAMP TIMESTAMP NOT NULL,
	DELETION_TIMESTAMP   TIMESTAMP NOT NULL,
	DATA                 MEDIUMTEXT
);