/*
 * Copyright (C) 2024 trustbroker.swiss team BIT
 * 
 * This program is free software.
 * You can redistribute it and/or modify it under the terms of the GNU Affero General Public License
 * as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * 
 * See the GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>. 
 */
package swiss.trustbroker.config.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Calculating unsafe-hashes:
 * <code>echo -n 'myscript()' | openssl sha256 -binary | openssl base64</code>
 * Risks: A thus whitelisted script could be injected in other parts of the page by an attacker.
 * We use this for the scripts generated by libraries (SAML auto-submitting form).
 *
 * @See https://content-security-policy.com/hash/
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ContentSecurityPolicies {

	private static final String DEFAULT_CSP = "default-src 'self'";

	private static final String SCRIPT_SRC_SELF = "; script-src 'self'";

	private static final String SAML_CSP = null;
			// inline script for OpenSAML: document.forms[0].submit()
			// CSP disabled because SLO generates a dynamic script in the header from SLO-Notifications.vm, 
			// this would either need to be externalized or a dynamic unsafe-hashes would need to be generated

	@SuppressWarnings("java:S125")
	private static final String OIDC_CSP = null;

	// UI has inline scripts and styles - would need to allow 'unsafe-inline' which does not prevent XSS -> don't enable for now
	private static final String FRONTEND_CSP = null;

	/**
	 * Default CSP configuration.
	 * <br/>
	 * Default: default-src 'self'
	 */
	@Builder.Default
	private String fallback = DEFAULT_CSP;

	/**
	 * CSP configuration for OIDC.
	 * <br/>
	 * Default: null
	 */
	@Builder.Default
	private String oidc = OIDC_CSP;

	/**
	 * CSP configuration for SAML.
	 * <br/>
	 * Default: null
	 */
	@Builder.Default
	private String saml = SAML_CSP;

	/**
	 * CSP configuration for frontend URLs.
	 * <br/>
	 * Default: null
	 */
	@Builder.Default
	private String frontend = FRONTEND_CSP;

}
