server:
  port: 5050
  servlet:
    session:
      tracking-modes: COOKIE

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          XTB-dev:
            registration:
              client-id: XTB-dev
              client-secret: "{noop}secret"
              client-authentication-methods:
                - client_secret_post
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
                - client_credentials
              redirect-uris:
                - http://localhost:4200/api/v1/oidc/response/access-log-tracking-only
                - https://oidcdebugger.com/debug
              scopes:
                - openid
                - profile
                - email
            require-authorization-consent: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.server.authorization.web: TRACE
